spring:
  application:
    name : stock

  profiles:
    active: main
  config:
    import: optional:configserver:http://admin:1234@localhost:9000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3307/stockStock?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true&profileSQL=true
    username: root
    password: 994499
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50 #최대 pool 크기
      minimum-idle: 20 #최소 pool 크기
      idle-timeout: 600000 #연결위한 최대 유후 시간
      max-lifetime: 1800000 #반납된 커넥션의 최대 수명

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://admin:1234@localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
  level:
    org:
      springframework:
#        jdbc:
#          core: DEBUG
    root: DEBUG

server:
  port: ${server.port}