spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3307/stockStock?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true&profileSQL=true
    username: root
    password: 994499

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://172.17.0.1:3306/stockStock?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true&profileSQL=true
    username: root
    password: 994499

---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  batch:
    job:
      enabled: true
      name: ${job.name:NONE}

  logging:
    level:
      org.hibernate.SQL: debug

logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
