spring:
  profiles:
    active: dev # 사용할 프로파일 선택

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3307/stockStock_dev?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true&profileSQL=true
    username: your_username
    password: your_password

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/stockStock_prod?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true&profileSQL=true
    username: your_username
    password: your_password
---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  batch:
    job:
      enabled: true
      name: ${job.name:NONE}

  logging:
    level:
      org.hibernate.SQL: debug

logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
