server:
  port: 8080


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://admin:1234@localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
        routes:
          - id: user
            uri: http://localhost:8081
#            uri: lb://MS
            predicates:
              - Path=/api/user/**
          - id: activity
            uri: http://localhost:8082
            predicates:
              - Path=/api/activity/**
          - id: newsFeed
            uri: http://localhost:8083
            predicates:
              - Path=/api/newsFeed/**
          - id: stock
            uri: http://localhost:8084
            predicates:
              - Path=/api/stock/**