spring:
  application:
    name: newsFeed
  profiles:
    include:
      - database
    active: main
  config:
    import: optional:configserver:http://admin:1234@localhost:9000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://admin:1234@localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: ${server.port}

resilience4j:
  circuit breaker:
    configs:
      default:
        failureRateThreshold: 10
        slowCallRateThreshold: 10
        slowCallDurationThreshold: 3000
        permittedNumberOfCallsInHalfOpenState: 3
        maxWaitDurationInHalfOpenState: 3000
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10000
    instances:
      customCircuitBreaker:
        baseConfig: default