spring:
  datasource:
    url: jdbc:mysql://localhost:3307/stockNewsFeed?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 994499
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6380
      timeout: 10